# -*- coding: utf-8 -*-
"""life_expentancy.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jGwRNz87VgNih-foPPFjf5xnbwH0szeb
"""

import pickle
import streamlit as st

model = pickle.load(open('life_expectancy.sav', 'rb'))

st.title('Estimasi Angka Harapan Hidup')

Year = st.number_input('Input Tahun')
Hepatitis_B = st.number_input('Input persentase orang yang sudah vaksin Hepatitis B')
Measles = st.number_input('Input persentase orang yang sudah vaksin Campak')
Polio = st.number_input('Input persentase orang yang sudah vaksin Polio')
Diphtheria = st.number_input('Input persentase orang yang sudah vaksin Difteria')
alcohol_consumption = st.number_input('Input jumlah orang Mengonsumsi Alkohol')
Incident_HIV = st.number_input('Input jumlah orang mengidap HIV')
BMI = st.number_input('Input BMI orang tersebut')

predict = ''

if st.button('Hitung Estimasi'):
    predict = model.predict(
        [[Year, Hepatitis_B, Measles, Polio, Diphtheria, alcohol_consumption, Incident_HIV, BMI]]
    )
    st.write ('Estimasi angka harapan hidup adalah : ', predict)
